application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout


from core.views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    url(r'^topics/', include('topics.urls', namespace="topics")),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^search/', include('haystack.urls', app_name='search', namespace='search')),

]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^login/', login, {'template_name': 'login.html'}, name="login"),
    url(r'^logout/', logout, {'next_page': 'index'}, name="logout"),
]

questions/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', QuestionList.as_view(), name="question_list"),
    url(r'^(?P<pk>\d+)/$', QuestionDetail.as_view(), name="question_view"),
    url(r'^create/$', QuestionCreate.as_view(), name="question_create"),
    url(r'^(?P<pk>\d+)/update/$', QuestionUpdate.as_view(), name="question_update"),
    url(r'^(?P<pk>\d+)/ajax.js/$', QuestionCommentAjax.as_view(), name="question_ajax"),
    url(r'^(?P<pk>\d+)/likes_ajax.js/$', QuestionLikesAjax.as_view(), name="likes_ajax"),

]

questions/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.dispatch import receiver

from comments.models import Comment
from topics.models import Topic
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class Like(models.Model):

    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    item_type = models.ForeignKey(ContentType)
    item_id = models.PositiveIntegerField()
    item = GenericForeignKey('item_type', 'item_id')


class Question(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=255, verbose_name=u'Заголовок вопроса')
    text = models.TextField(verbose_name=u'Содержание вопроса')
    pub_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    topics = models.ManyToManyField(Topic, related_name='questions')
    image = models.ImageField(blank=True, null=True)
    likes_count = models.IntegerField(default=0)

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'
        ordering = ('-pub_date', )

    def __unicode__(self):
       return self.title


@receiver(models.signals.post_save, sender=Comment)
def on_answer_creation(sender, instance, *args, **kwargs):
    if kwargs.get('created'):
        answer = instance
        from .tasks import send_email_notification
        send_email_notification.delay(
            'd.isaev@corp.mail.ru',
            'New answer to question "{}"'.format(answer.question.title),
            'You got answer with the text: "{}"'.format(answer.text)
        )

questions/forms.py
# coding: utf-8
from django import forms


class QuestionListForm(forms.Form):

    search = forms.CharField(required=False, initial='Поиск')
    sort_field = forms.ChoiceField(choices=(('id', 'ID'), ('pub_date', u'Дата создания'), ('is_published', u'Неопубликованные')), required=False, initial=id)
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(QuestionListForm, self).form_valid(form)


class QuestionForm(forms.Form):

    title = forms.CharField(max_length=255 )
    text = forms.CharField()

questions/views.py
# coding: utf-8
from django.shortcuts import resolve_url, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from comments.models import Comment
from .models import Question
from .forms import QuestionListForm
from django.db.models import Q
from django.db.models import Count
from django.http import JsonResponse


class QuestionCreate(CreateView):

    model = Question
    template_name = "questions/create.html"
    fields = ('title', 'text', 'topics', 'is_published')

    def get_success_url(self):
        return resolve_url('questions:question_view', pk=self.object.pk)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(QuestionCreate, self).form_valid(form)


class QuestionUpdate(UpdateView):

    model = Question
    template_name = "questions/update.html"
    fields = ('title', 'text', 'is_published')

    def get_success_url(self):
        return resolve_url('questions:question_view', pk=self.object.pk)


class QuestionList(ListView):

    model = Question
    template_name = "questions/question_list.html"
    context_object_name = 'questions'

    def dispatch(self, request, *args, **kwargs):
        self.form = QuestionListForm(request.GET)
        self.form.is_valid()
        self.search = self.form.cleaned_data.get('___')
        self.sort_field = self.form.cleaned_data.get('sort_field')
        return super(QuestionList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuestionList, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def get_queryset(self):
        queryset = super(QuestionList, self).get_queryset()
        if self.request.user.is_authenticated():
            queryset = queryset.filter(Q(author=self.request.user) | Q(is_published=True))
        else:
            queryset = queryset.filter(is_published=True)
        if self.search:
            queryset = queryset.filter(Q(title__icontains=self.search) | Q(text__icontains=self.search))
        if self.sort_field:
            queryset = queryset.order_by(self.sort_field)
        queryset = queryset.annotate(comments_count=Count('comments__id'))
        return queryset


class QuestionCommentAjax(DetailView):

    template_name = 'questions/question_comment_ajax.html'
    model = Question
    context_object_name = 'question'


class QuestionLikesAjax(DetailView):

    template_name = 'questions/question_likes_ajax.html'
    model = Question
    context_object_name = 'question'


class QuestionDetail(CreateView):
    model = Comment
    template_name = 'questions/question_detail.html'
    fields = ('text', )

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.question = get_object_or_404(Question, id=pk)
        return super(QuestionDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['question'] = self.question
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.question = self.question
        return super(QuestionDetail, self).form_valid(form)

    def get_success_url(self):
        return resolve_url('questions:question_view', pk=self.question.pk)

questions/templates/questions/create.html
{% extends "base.html" %}
{% load bootstrap %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-lg-5 well">
        <form method="post">
            {%  csrf_token %}
            {{ form.title | bootstrap}}
            {{ form.text | bootstrap}}
            {{ form.is_published | bootstrap}}
            {{ form.topics|add_class:'form-control chosen-select'}}
            <button class="btn btn-primary btn-block" type="submit">Создать вопрос</button>
        </form>
    </div>
{% endblock %}

questions/templates/questions/question_comment_ajax.html
<div class="row marketing">
    <div class="col-lg-6">
        <h1> Комментарии </h1>
        {% for comment in question.comments.all %}
            <div class="container well col-lg-4">
                <div>{{comment.text}}</div>
                <div id="comment_date"><i class="icon-clock2"></i> {{ question.pub_date}}</div>
                <div id="comment_author">Автор: {{comment.author}}</div>
            </div>
        {% endfor %}
    </div>
</div>

questions/templates/questions/question_detail.html
{% extends "base.html" %}
{% load static%}
{% load bootstrap %}

{% block title %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-5 well">
            <div><h3>{{ question.title }}</h3></div>
            <div>Текст: {{ question.text }}</div>
            <div>Дата публикации: {{ question.pub_date}}</div>
            <div>Топики:{% for topic in question.topics.all %} {{ topic }}{% endfor %}</div>
            <div>Автор: {{ question.author }}</div>
            <div>
                {% if question.is_published == True %}
                    <span class="label label-primary">Опубликован</span>
                {% else %}
                    <span class="label label-warning">Не опубликован</span>
                {% endif %}
            </div>
            <img src="{{ question.image}}">
            <div>
                <a id="to_like" data-like="{% url "questions:likes_ajax" pk=question.pk%}" class="icon">
                    <span class="glyphicon glyphicon-heart"></span>
                </a>
                <div id="likes" ></div>
            </div>
        </div>
    </div>

    {% if question.author == user %}
        <div><strong><a href="{% url "questions:question_update" pk=question.pk %}">Редактировать</a></strong></div>
    {% endif %}

    <div class="row">
        <div id="comments"></div>
        <div data-update-from="{% url "questions:question_ajax" pk=question.pk%}"></div>
    </div>

    <div class="row col-md-4">
    {% if user.is_authenticated %}
            <form id="fff" method="post">
                {% csrf_token %}
                {{ form.errors }}
                {{ form|bootstrap }}
            <button class="btn btn-primary btn-block" type="submit">
                <span class="glyphicon glyphicon-comment"></span>
                Комментировать
            </button>
            </form>
    {% endif %}
    </div>

{% endblock %}

questions/templates/questions/question_likes_ajax.html
<div>{{question.likes_count}}</div>

questions/templates/questions/question_list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
 <div class="row p-b">
     <div class="col-lg-9">
             <div class="row panel panel-default">
            {% for question in object_list %}
                <div class="col-md-4 col-sm-6 col-xs-6 col-xxs-12 well">
						<div>
							<div class="fh5co-post-text">
								<h2><a href="{% url 'questions:question_view' pk=question.pk %}">{{ question.title }}</a></h2>
								<p>{{ question.text }}</p>
							</div>
							<div class="fh5co-post-meta">
                                <div><a>
                                {% if question.is_published == True %}
                                     <span class="label label-primary">Опубликован</span>
                                {% else %}
                                     <span class="label label-warning">Не опубликован</span>
                                {% endif %}
                                </a></div>
								<a href="#"><i class="icon-life-ring"></i>{{ question.likes_count }}</a>
								<a href="#"><i class="icon-scissors"></i>{{ question.comments_count }}</a>
								<a href="#"><i class="icon-clock2"></i> {{ question.pub_date}}</a>
							</div>
						</div>
					</div>
            {% endfor %}
            </div>

        </div>

        <div class="col-lg-2 sidebar-offcanvas" id="sidebar">
            <form class="navbar-form navbar-left navbar-header">
                {{ form|bootstrap }}
                <button class="btn btn-sm btn-primary btn-block" type="submit">Искать</button>
            </form>
        </div>
 </div>
{% endblock %}

questions/templates/questions/update.html
{% extends "base.html" %}
{% load bootstrap %}


{% block content %}
<form method="post">
    {%  csrf_token %}
     <div class="col-lg-5 well">
        {{ form|bootstrap }}
        <button class="btn btn-primary btn-block" type="submit">Обновить вопрос</button>
     </div>
</form>
{% endblock %}