application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout


from core.views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    url(r'^topics/', include('topics.urls', namespace="topics")),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^search/', include('haystack.urls', app_name='search', namespace='search')),

]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^login/', login, {'template_name': 'login.html'}, name="login"),
    url(r'^logout/', logout, {'next_page': 'index'}, name="logout"),
]

questions/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', QuestionList.as_view(), name="question_list"),
    url(r'^(?P<pk>\d+)/$', QuestionDetail.as_view(), name="question_view"),
    url(r'^create/$', QuestionCreate.as_view(), name="question_create"),
    url(r'^(?P<pk>\d+)/update/$', QuestionUpdate.as_view(), name="question_update"),
    url(r'^(?P<pk>\d+)/ajax.js/$', QuestionCommentAjax.as_view(), name="question_ajax"),
    url(r'^(?P<pk>\d+)/likes_ajax.js/$', QuestionLikesAjax.as_view(), name="likes_ajax"),

]

topics/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', TopicList.as_view(), name="topic_list"),
]

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
from django.views.generic import TemplateView
from questions.models import Question
from comments.models import Comment



class IndexView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['last_questions'] = Question.objects.filter(is_published=True)[:5]
        context['last_answers'] = Comment.objects.filter(question__is_published=True)[:5]
        return context

core/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


      <!--FROM TEMPLATE-->
                      <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <title>Project Narrator</title>
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
                    <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
                    <meta name="author" content="FREEHTML5.CO" />

                    <!-- Google Fonts -->
                    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Monsterrat:400,700|Merriweather:400,300italic,700' rel='stylesheet' type='text/css'>

                    <!-- Animate.css -->
                    <link rel="stylesheet" href="../static/css/animate.css">
                    <!-- Icomoon Icon Fonts-->
                    <link rel="stylesheet" href="../static/css/icomoon.css">
                    <!-- Magnific Popup-->
                    <link rel="stylesheet" href="../static/css/magnific-popup.css">
                    <!-- Owl Carousel -->
                    <link rel="stylesheet" href="../static/css/owl.carousel.min.css">
                    <link rel="stylesheet" href="../static/css/owl.theme.default.min.css">
                    <!-- Bootstrap  -->
                    <link rel="stylesheet" href="../static/css/bootstrap.css">

                    <!-- Cards -->
                    <link rel="stylesheet" href="../static/css/cards.css">

                    <!-- Modernizr JS -->
                    <script src="../static/js/modernizr-2.6.2.min.js"></script>
                    <!-- FOR IE9 below -->
                    <!--[if lt IE 9]>
                    <script src="js/respond.min.js"></script>
                    <![endif]-->
      <!--                      -->
      <meta charset="UTF-8"><script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>

      <link href="assets/css/get-shit-done.css" rel="stylesheet" />
    <link href="assets/css/demo.css" rel="stylesheet" />

    <!--     Font Awesome     -->
    <link href="bootstrap3/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>

      <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

      <script src="{% static 'js/base.js' %}"></script>
      <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

  </head>


  </head>

  <body>

    <div class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'index'%}">Project Narrator</a>
                    </div>
                    <div class="collapse navbar-collapse" id="responsive-menu">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'questions:question_list'%}">
                                <span class="glyphicon glyphicon-folder-open"></span>
                                Вопросы
                            </a></li>
                            <li><a href="{% url 'topics:topic_list'%}">               <!-- ДОПИЛИТЬ ТОПИКИ -->
                                <span class="glyphicon glyphicon-folder-open"></span>
                                Топики
                            </a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url "questions:question_create" %}">
                                    <span class="glyphicon glyphicon-send"></span>
                                    Задать вопрос
                                </a></li>
                               <li><a href="{% url "core:logout" %}?next={% url 'core:logout' %}">
                                   <span class="glyphicon glyphicon-log-out"></span>
                                   Выйти
                                   </a>
                               </li>
                               <li><a href="#">
                                   <span class="glyphicon glyphicon-user"></span>
                                   {{ user.username }}
                               </a></li>
                            {% else %}
                             <li>
                                 <a href="{% url "core:login" %}?next={{ request.get_full_path }}">
                                     <span class="glyphicon glyphicon-log-in"></span>
                                     Войти
                                 </a>
                             </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
    </div>

    {% block title %}{% endblock %}
    <div class="container">

        {% block content %}{% endblock %}
    </div>


    <hr>


    <div class="container">
        <footer>
            <div id="content">
                <a href="#open" id="open">О нас</a>
            </div>
            <div id="ok-dialog" class="ui-dialog-titlebar ui-widget-header">
                <p>Что-то о нас</p>
            </div>
        </footer>
   </div>


    <script src="../static/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="../static/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="../static/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
   <script src="../static/js/jquery.waypoints.min.js"></script>
	<!-- Owl Carousel -->
	<script src="../static/js/owl.carousel.min.js"></script>
	<!-- Magnific Popup -->
	<script src="../static/js/jquery.magnific-popup.min.js"></script>
	<!-- Stellar -->
	<script src="../static/js/jquery.stellar.min.js"></script>
	<!-- countTo -->
	<script src="../static/js/jquery.countTo.js"></script>
	<!-- WOW -->
	<script src="../static/js/wow.min.js"></script>
	<script>
		new WOW().init();
	</script>
	<!-- Main -->
	<script src="../static/js/main.js"></script>


  </body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% block title %} <div class="fh5co-cover fh5co-cover-style-2 js-full-height" data-stellar-background-ratio="0.5" data-next="yes"  style="background-image: url(../static/images/full_1.jpg);">
		  	<span class="scroll-btn wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.4s">
				<a href="#">
					<span class="mouse"><span></span></span>
				</a>
			</span>
			<div class="fh5co-overlay"></div>
			<div class="fh5co-cover-text">
				 <div class="container">
                    <div class="row">
                        <div class="col-md-push-6 col-md-6 full-height js-full-height">
                            <div class="fh5co-cover-intro">
                                <h1 class="cover-text-lead wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">Какой-то заголовок</h1>
                                <h2 class="cover-text-sublead wow fadeInUp" data-wow-duration="1s" data-wow-delay=".8s">Какой-то текст</h2>
                                {% if user.is_authenticated %}
                                <p class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.1s">
                                    <a href="{% url "questions:question_create" %}" class="btn btn-primary btn-outline btn-lg">Задать вопрос</a>
                                </p>
                                {% else %}
                                <p class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.1s">
                                    <a href="{% url "core:login" %}?next={{ request.get_full_path }}" class="btn btn-primary btn-outline btn-lg">Войти, чтобы задать вопрос</a>
                                </p>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
{% endblock %}
{% block content %}
{% endblock %}

core/templates/login.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}{% endblock %}

{% block content %}

     <div class="row marketing ">
        <div class="col-lg-4 well ">
            <form method="post">
                {% csrf_token %}
                {{form|bootstrap}}
                <button class="btn btn-primary btn-block" type="submit">Войти</button>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/logout.html
Пока :,(